repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.3
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]

  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length, "110"]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile, "black", --skip, "venv"]
